kubernetes_users_emails:
    - ENC[AES256_GCM,data:tqxmXATZsusIFAXBEmNp7uAeoltdwouJwmHrXlks,iv:lF0TgrnxMGYCyvBHntAp8tVcsEwqOd6kWGa4EPspbc4=,tag:j+1Le054c4lJSGiW9UncEQ==,type:str]
    - ENC[AES256_GCM,data:+GqtnxX4k3SOD358n/ziDa+EZd6tLxucbqGK5Gcql0HhMQ==,iv:4Xuu8EXwrDv4YisaWuMtJhaAaRhpsI19yUAACXzk9nA=,tag:JDd5Zhk8io0x+RRvoHl6YQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWE5qaVd2Z04wNk0rT04w
            STQxaHl5S21pdnJoOVFiaWoxRnV4YnkwZXcwCjBXNm9KOFdaYWpkNFYrc3c5L0pJ
            SEtJRHJxQXpkYzBuL002c05QY1JPMW8KLS0tIGloR3Z3WENlT0wzcVZVbFcvTmtk
            SjJFdzQxdzhRM1hxR3FyRHhSRi9xYkEKmjXgvxpmfoOq5snH7bCRCr9pHWKTjL1x
            dSpE6N6SO8qwByf/wUGmI/Et12MbDwpT1vytM37iC1Q+p8zXPP81Vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9qyhryg9zmwywfy92468knc2n5zr2j66e73kw5mzc28fs6m5u4qpazpma
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgTlFubmJ3IEJJNVd0L1cw
            b041L0lLR1EvZ2dvVXdKRkY2cmVhb2tsdVIvVHBPL0xURjlYM2lDd2hhVkZlaWM1
            S3Y1TzVoc0RCVW9Wb1hlWWFEVWllKzFOc2hYVjB4RQpNdmJmY2RRWW9WREdvcUw0
            WlNHcDV1N2NwdWRMWk5hTmcySlRPUHUrOEhjCi0tLSBuUnIweXgvLzY4NEsvdGdk
            OEJzc1JTaUFMenlCTWFDT1dYUnpxYkNyVURrCq18txjHfujgtnoQod3tVamnHCsI
            lBSa4tSOztp5dT7pOhBYWgFj/suugXTg4zlwN5BZBhGSGt/bmI4LElsDKVU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1q22yv67hk89v390rseukrx3mu5gzw9lpnngla4shn3efhzg2czn7cvdt8y3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxemlDcTlCS2JUaEpZMjl1
            RTNOdUY4cmRiR2RGVUFUN2QwTWVHTXdzdVZvClQxQjFTZTJTcm9rYjd6V2hxclda
            eWRhcVlEK1pncDlJV0RadlVsZ0s0L2cKLS0tIExkQmNwOVZQMXpFSmdPN0p3M0tV
            T1RmZ29Kd1hJM2hCM2oxV1pGdlIxb0kKxUnnz0qXcXSEMtEz74uiBnzUWEsw+EB/
            SlewAK93tTCkcFn1NE8lEskY3nRyzWMEpZCZIrm4+xQgHTxrse5aLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q2w07qws7tw5fhcsnxr33z6588exfnu2dpnsqhhqlvyxc0jf750qgrwv5t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgeEdLM01nIEJHMHJJZG9F
            aExheTBJdUt2ODVxN2hsVU1EMmwxc3JZcTNCTkdwSnF2ZXJ0a1k1RkZtZFZETDFH
            U1Z2d3VlNDkzU3FCVGliQm90L1NGNjZaV0NzRy8wNApLRUhQU0ZTajcrajNzdHRz
            WDFScjcyZG1yTi9ZS29memgrSHY1YmhGeHhFCi0tLSA5UVpuUHAzekorWEFtMU4v
            b3UzSDJMT3Z4QTBjRll3RmVabGgwR2dJNzFvChzTtBRzhENPs6xAfUZrUwPOuvQx
            z0Wjh3zjU7ApgMELMxPZ4KJbtGMIN2zsarV5gMrh1tF38yb9oHOgJoc5Gd8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tpm1qdeuratg9kfm728u6kd278g7alwz3n6esmf4szyjcuwgrhqmlt0qg9u33se
    lastmodified: "2026-06-12T20:38:15Z"
    mac: ENC[AES256_GCM,data:U39gBQAZUywn1JWG3fJtOaPmwiarYc/3d5ANqc0daIVahYQEXj4UOnujGuGA4g3bolNLcYmoe6X3SL+vA97aS27xvwe21ufcam3BsKgMAE45HLMpwRpc3nWpVCtcwLeUEx5Ipt/eR9D+LB6tG20oIm6YgIUUb/yZEMVo19DSAGU=,iv:M1a7QXSmInPZyuEdQjOWO0hHaCRa/w3EnuirOJ57Gjc=,tag:0WfdZEetCa2WPFhsj9XO1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
