kubernetes_users_emails:
    - ENC[AES256_GCM,data:tqxmXATZsusIFAXBEmNp7uAeoltdwouJwmHrXlks,iv:lF0TgrnxMGYCyvBHntAp8tVcsEwqOd6kWGa4EPspbc4=,tag:j+1Le054c4lJSGiW9UncEQ==,type:str]
    - ENC[AES256_GCM,data:+GqtnxX4k3SOD358n/ziDa+EZd6tLxucbqGK5Gcql0HhMQ==,iv:4Xuu8EXwrDv4YisaWuMtJhaAaRhpsI19yUAACXzk9nA=,tag:JDd5Zhk8io0x+RRvoHl6YQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWnlZLzhWbkZJdzBUcVla
            dk5MbStCS2M3V1VsNUVqTGRPalZwblBhL0ZVCmtoV25aeFdwRS9WN3QwL0lDR0Ev
            NjkyOE5Sd1VCNGxLVjBVaEZ4aXdra00KLS0tIFF2VTQzRXJzQzRKZ0pIVEFLNlZH
            RjZoeFBxOHAyUHdqR0xDL0EyTm5qWm8KIyWdtKy75nQV2R/OD3jj41n/ywN+NaLp
            coIH4HUwNUVytkHHEuLEfPeDmUKeJRHh4k27m2kYfKciXQXLInzMfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9qyhryg9zmwywfy92468knc2n5zr2j66e73kw5mzc28fs6m5u4qpazpma
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RkZ0Y3ByVmFwN1hycEcz
            V1E2OXZSYmR5U0hiYm9RTGozMjYyekx0eVZ3CjBPMFNpZ3ZRNmdzK003RHNPUGJq
            UEFxM3FlcjJPeDE1ZTB5OGorVDVuaGsKLS0tIEpJUUhxKzhDeXF0MmVYQnhsOWtJ
            VzFLbUtJZnRRcUdCYktkaTZGd2tSK1UKhEu0qXQlD8aQqcj/6lgxbl4wRfHOivBu
            kUvf8RIVpzkSY2uF0MQ45ORArEtbGSib9zif8Tr2epxjbO4/l6NP7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q2w07qws7tw5fhcsnxr33z6588exfnu2dpnsqhhqlvyxc0jf750qgrwv5t
    lastmodified: "2026-06-12T20:38:15Z"
    mac: ENC[AES256_GCM,data:U39gBQAZUywn1JWG3fJtOaPmwiarYc/3d5ANqc0daIVahYQEXj4UOnujGuGA4g3bolNLcYmoe6X3SL+vA97aS27xvwe21ufcam3BsKgMAE45HLMpwRpc3nWpVCtcwLeUEx5Ipt/eR9D+LB6tG20oIm6YgIUUb/yZEMVo19DSAGU=,iv:M1a7QXSmInPZyuEdQjOWO0hHaCRa/w3EnuirOJ57Gjc=,tag:0WfdZEetCa2WPFhsj9XO1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
