kubernetes_users_emails:
    - ENC[AES256_GCM,data:tqxmXATZsusIFAXBEmNp7uAeoltdwouJwmHrXlks,iv:lF0TgrnxMGYCyvBHntAp8tVcsEwqOd6kWGa4EPspbc4=,tag:j+1Le054c4lJSGiW9UncEQ==,type:str]
    - ENC[AES256_GCM,data:+GqtnxX4k3SOD358n/ziDa+EZd6tLxucbqGK5Gcql0HhMQ==,iv:4Xuu8EXwrDv4YisaWuMtJhaAaRhpsI19yUAACXzk9nA=,tag:JDd5Zhk8io0x+RRvoHl6YQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNVpnUmpudkhnVWdRS210
            TTN5VlZGU0V1b3VZUWo4RFg2d01mbDhKZHp3CmJ3Um5OdDByZjY5UHhrbXFRVmts
            WkJVaVVmK2pibzVDSHJzQ0N5SXV3dlEKLS0tICszVVVKT0ZvZzRjampkVWYrRzZa
            OE5UVmVUeVMrbmNZcVI1K1c4YnNRNzAKtH4xgr3eigrAw8xyLrIWZXyNM41vmGXE
            f0D/cek/PEzbqC7fQridV6r5xYmiy60qzlRKGFRoSfMxI9FS71Mxgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9qyhryg9zmwywfy92468knc2n5zr2j66e73kw5mzc28fs6m5u4qpazpma
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgOVBTaXdBIEJHK0N4cHBO
            dzhiSWR0eklPMlp3eDhJT25TSjNydEQ3c2FvOHhIWlUzTXpXc2xXQkEvYVNQU0VT
            K24zYjYwSDBFM1pMZHl2d3kwSzFtWi9Ib0EyRDZtQQp6SWwyekJyTlhoRE1nMTI4
            SmRLVFg4Z0M5Q3lvUnhlVUI1a2s5aDdtUU1RCi0tLSBibkpsUTZrUXpJRm8xVDdu
            RHBJY1BLNnY1Rk8wN3pid2RqeDE1VXo4eHpvCk8L0CgzKSRmsiiP3UJ2KtQL0RAP
            Q4H5xoI95xgszSyxi2FWKnak5ZCyB3zRuKV8OqpeNLN/snX8dOp+i/cnC8E=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1q22yv67hk89v390rseukrx3mu5gzw9lpnngla4shn3efhzg2czn7cvdt8y3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ek5zMTJPWmVpbkd1dTBT
            VHpPQXlFNFBBUHFYZFd4YUhYYUVkVTFvV21zCjVoSktPSWQra2tSRkJGVGZvSVo1
            dFVMSFJvelJ3VUJJaXE0bi9xZEI4QUkKLS0tIDY2S1djVHY4clJQa1FxQ3Mvemgz
            L04rempka2NkY0d6MkJOYm5JNXRqRjAKPUvR3wgkpBNEpxRf+jNYrc04L4WXaR+7
            ZxDYtWl5HLo5Xdjxr2hXrfqqEkGnB3FJMQtSdplsjA9fTZslvHI9bA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q2w07qws7tw5fhcsnxr33z6588exfnu2dpnsqhhqlvyxc0jf750qgrwv5t
    lastmodified: "2026-06-12T20:38:15Z"
    mac: ENC[AES256_GCM,data:U39gBQAZUywn1JWG3fJtOaPmwiarYc/3d5ANqc0daIVahYQEXj4UOnujGuGA4g3bolNLcYmoe6X3SL+vA97aS27xvwe21ufcam3BsKgMAE45HLMpwRpc3nWpVCtcwLeUEx5Ipt/eR9D+LB6tG20oIm6YgIUUb/yZEMVo19DSAGU=,iv:M1a7QXSmInPZyuEdQjOWO0hHaCRa/w3EnuirOJ57Gjc=,tag:0WfdZEetCa2WPFhsj9XO1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
