strongswan_private_network_subnet: ENC[AES256_GCM,data:mV9uYV/2pZDpI0zyCQ==,iv:iRQ5n71JsYm715L4OqYVZRJBJQNalifBcjMyliRuL7o=,tag:L3PQC9ZUTpBBwWnpOBcKiA==,type:str]
strongswan_private_network_public_gateway_ip: ENC[AES256_GCM,data:pvdM71hQPiU7aw==,iv:xN2j7airwNtDYn+Twv+h8BX5m3HU9eQ404d9F8lFeOI=,tag:CdFT2wM6Zn0EJGVgFHDV0w==,type:str]
kubernetes_private_network_subnet: ENC[AES256_GCM,data:nAUaPzeeOata5ckCXA==,iv:0/bUVETn/WA7dWC9C/wt0HzKPQWe3vkhvnM6pyvBU/w=,tag:okz8FNWb9hLLa0UdzcYxsw==,type:str]
kubernetes_private_network_public_gateway_ip: ENC[AES256_GCM,data:6/C6BDL4wGAMjg==,iv:Ubiwz5w/l/5PmTLydg9J2lJQmvKUodLssK+E2PsF9bg=,tag:Zp2bPIMj4qUjXljkFvyPhg==,type:str]
sops:
    age:
        - recipient: age1q9qyhryg9zmwywfy92468knc2n5zr2j66e73kw5mzc28fs6m5u4qpazpma
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWmlxakRFSVc5dFdXRTYz
            NzZqQVNUWHprT1R5a0dBRU52aGpFd2Fkd0hVCldPZzQ5UWFCd0NiVzkrRHpmVmtt
            am40OE5DSU5PZVhjVmZkQWVUcERrUFEKLS0tIElub2c3WHJMZHhyb1MxclFhT3dB
            QVVQTjRxWDd0WExzdnBZRkFya0IrU28KYBgCMDndRy/8N+DOm56DOIsMYJmll19R
            Ydr1HjChicHZopn7YP3Y/WSbaLXUS2gjQCo44xwRfFlWxQHc6KAaHw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q2w07qws7tw5fhcsnxr33z6588exfnu2dpnsqhhqlvyxc0jf750qgrwv5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Z2V1TUo0cWszTWxidE1L
            UWZXVXZ6WWl0UVByaEcxUXdZTitmd1VTWlQwClU1Y1Byc2FESlUvMElQNGlTcHpy
            bld3d2I3VXEwRVlPUmM3U0Nqckh1ZEUKLS0tIDIzSGZQUkFzMU1tZnJWR1Q1Q01T
            SmhzT2pNcmlqa21sY3JZNnFYUUdwS28KR646zCBERiqWB8cC15+W7TNLEDryxsKR
            9/ubaO14rIVfHQ1CUgGfvv0q8YGIGnWxf/QEsocOyFQRFg5kUB9FMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T15:15:26Z"
    mac: ENC[AES256_GCM,data:6r89rR+1WDPEIISWSUZuCNZzuYDEbKksQwDTZoHBBjiCe9fKQCIHRa7TP74/POtFZl3ayRAItBSJq3HnmnCpgkwVSxS3H0fxF92gWWDE95gyU4LOiNgfszIivSMIN6vAYGHye1UexacagBFinPoNyhtd6KxFAYDJMtqW+S46uNI=,iv:T65glM9sNjkf/QdlARVPHC3XMVYppQDYJVRjqOHK6es=,tag:Zu7cD3lshIzwK568Nf+xnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
