strongswan_private_network_subnet: ENC[AES256_GCM,data:mV9uYV/2pZDpI0zyCQ==,iv:iRQ5n71JsYm715L4OqYVZRJBJQNalifBcjMyliRuL7o=,tag:L3PQC9ZUTpBBwWnpOBcKiA==,type:str]
strongswan_private_network_public_gateway_ip: ENC[AES256_GCM,data:pvdM71hQPiU7aw==,iv:xN2j7airwNtDYn+Twv+h8BX5m3HU9eQ404d9F8lFeOI=,tag:CdFT2wM6Zn0EJGVgFHDV0w==,type:str]
kubernetes_private_network_subnet: ENC[AES256_GCM,data:nAUaPzeeOata5ckCXA==,iv:0/bUVETn/WA7dWC9C/wt0HzKPQWe3vkhvnM6pyvBU/w=,tag:okz8FNWb9hLLa0UdzcYxsw==,type:str]
kubernetes_private_network_public_gateway_ip: ENC[AES256_GCM,data:6/C6BDL4wGAMjg==,iv:Ubiwz5w/l/5PmTLydg9J2lJQmvKUodLssK+E2PsF9bg=,tag:Zp2bPIMj4qUjXljkFvyPhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeDlhMVgvZlU2VUZrMEds
            U1QxZXZ1TkliT2tEMEVMTmFqWkNZZjhuUmtFClI1ZTZCUkV1aEZSZmpOTkcyU2Nt
            amZmSjZoeGpvNGtpQzBqRVg1NWo4Uk0KLS0tIHk3S0VJc0lZei9qZktpT1EzZGkr
            U2pra1IwTXp1aGdMRGh3Q2I4SDlFK0EKhVPsGz7rMgXJjbD5cFkGgHsE32C6U7wV
            hHvMHE/p+J4w3sfT1DCFaO9lr6lpSUMIPBji/u8p3xebavUVQ3141g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9qyhryg9zmwywfy92468knc2n5zr2j66e73kw5mzc28fs6m5u4qpazpma
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgSDZNRTV3IEJPMHFEcUNX
            bVRSM2FPb0hFeWlJOTNJdmxpTVo2dXNqeVV5RkRUbnRPaVMwWlNmRjVoT1lsb05y
            ekNvSVFiVWwrSW44TTlMYlVjYTR0VWhqMmdIVjdFVQpsaUlBNFZ4a2laanpPYjR1
            dDFXeTJTT0pJK0t0MjlxcWtrRHdmMzYvcE1BCi0tLSBQcWdhSWY4V3FmSDRpRTVp
            K2NjRFhlN3BVY01uUnhoc0x1QWlOOUQzNW80CmCv6ojNUnQBTiZnjfeT8Q8Tc4Iq
            9+iVqOphdNkHrUvjT+yf5jdoTihURpq3yIiRAzoR4HrZEy8nv1df6YGAB+g=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1q22yv67hk89v390rseukrx3mu5gzw9lpnngla4shn3efhzg2czn7cvdt8y3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaTZ3Z2hrVUhYZVpZamww
            T3FqSzB6dGFSMzZyT1EyLzVvYU1MZllkYXk0CkhGNUExeW9GVGM5OFRVait5a3RV
            MXhtcjZ1aUdaaXg5Qk11SllJUFhEMWsKLS0tIC8ydEVHMllKSXhZZE9wQkFKYWxs
            VS9yNnJhTkFWeEllbkdBeTR1bXh4SWcKN+jWJ+bsYqVkPxipJBsLIudCzwazRVOJ
            uzt33R0Phkp3vxDlja1cpJMJUHLmeokc4EjhZfxiTYgY7c+d17jMJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q2w07qws7tw5fhcsnxr33z6588exfnu2dpnsqhhqlvyxc0jf750qgrwv5t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcganF5bU1RIEJGODdMSGVz
            L2tLODJVTTRPZjZJVTE1RUw3Sy9wQ2xxMWxEMERBdmJEeFpMLzYzSHV0RTZnWkps
            NGdrRHVxY0pzUm0xZUo5YWVXSzBmSlYvYW5zUEtnNApESVdiY3dFOWIwUS9aaHhw
            a1dUbUk2cEp3d2RoOHlrSjRhTTFoamYwSytVCi0tLSBuUk1QV0NObHNLaDg2dUZH
            MFRkTmJIeE14bXVBS2ZZeFNXQmh2dVRrZm53CtSr8pv1SdMmxZjLZFlrgum/U0SR
            3KiEirSi1d+OVFETZfBdZBuOdIykkczZwZwAgaV0gbudbMmfJf4RJVMFyog=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tpm1qdeuratg9kfm728u6kd278g7alwz3n6esmf4szyjcuwgrhqmlt0qg9u33se
    lastmodified: "2026-05-07T15:15:26Z"
    mac: ENC[AES256_GCM,data:6r89rR+1WDPEIISWSUZuCNZzuYDEbKksQwDTZoHBBjiCe9fKQCIHRa7TP74/POtFZl3ayRAItBSJq3HnmnCpgkwVSxS3H0fxF92gWWDE95gyU4LOiNgfszIivSMIN6vAYGHye1UexacagBFinPoNyhtd6KxFAYDJMtqW+S46uNI=,iv:T65glM9sNjkf/QdlARVPHC3XMVYppQDYJVRjqOHK6es=,tag:Zu7cD3lshIzwK568Nf+xnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
