strongswan_private_network_subnet: ENC[AES256_GCM,data:mV9uYV/2pZDpI0zyCQ==,iv:iRQ5n71JsYm715L4OqYVZRJBJQNalifBcjMyliRuL7o=,tag:L3PQC9ZUTpBBwWnpOBcKiA==,type:str]
strongswan_private_network_public_gateway_ip: ENC[AES256_GCM,data:pvdM71hQPiU7aw==,iv:xN2j7airwNtDYn+Twv+h8BX5m3HU9eQ404d9F8lFeOI=,tag:CdFT2wM6Zn0EJGVgFHDV0w==,type:str]
kubernetes_private_network_subnet: ENC[AES256_GCM,data:nAUaPzeeOata5ckCXA==,iv:0/bUVETn/WA7dWC9C/wt0HzKPQWe3vkhvnM6pyvBU/w=,tag:okz8FNWb9hLLa0UdzcYxsw==,type:str]
kubernetes_private_network_public_gateway_ip: ENC[AES256_GCM,data:6/C6BDL4wGAMjg==,iv:Ubiwz5w/l/5PmTLydg9J2lJQmvKUodLssK+E2PsF9bg=,tag:Zp2bPIMj4qUjXljkFvyPhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYWlUT1JnZlBQTjA1NmVL
            QlppRVMrQlBWUExxREp0djA1bndvb3ZreVVZCkxSdkh5TTgzYVZLbkxoaVRXUnNV
            eEFGZS9YMFFPTFhBM2N3L2tMRU5KeEUKLS0tIHQ4eDJxaU5jZjZnQVY0dXFoWnZa
            TG1zVkJXWnBmMXpoV29uTndReDJXdmMKqz4WXv8pnUoEF3sRK9U9UvJJ3BoqL8i1
            Z5IdzAuKsktHozZ82DMuM5JWv0/u0VC+whtVxxGBG2Hv9MzSsqMNUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9qyhryg9zmwywfy92468knc2n5zr2j66e73kw5mzc28fs6m5u4qpazpma
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgN1BuR0Z3IEJFRERFazNU
            WURYZS9pd3hKTGM5bFBzREpHL2JIc1RzNUY5QmcraTdnQmJFeTNyc2FoMCtOR1hj
            UWcrTnhvVXMyVVpSRDhIQzYvUHQ1WUJqcGkySFp5awowcWFIeE0rMWQ2RHBWZnJ0
            OFdURjh5QlJNUlpCc01JZHRSNFFQdzlhZHFNCi0tLSBKM01YQnpPaHJoQTBSendz
            QlFFYXdiTHBIR25XaC9RWXRNL0I3ajNnNDhFCl7zSNF6BH2NC99QtACTZOEfQrUX
            EBN1rnuLwIGEC8cG63kOXxxgd6CIuQBx1S/ONDqHlLC2DCdjvR7P6DQ3Wzk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1q22yv67hk89v390rseukrx3mu5gzw9lpnngla4shn3efhzg2czn7cvdt8y3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQWVOa2tYTnNVWTlZR1Z6
            TllZc09hdHRwNkEvbDhvcVhLa0Y3Q3NMN0RzCjVDTzFoNHhmaXJ3eG9KbjQ3TGxl
            UzIwUGw3aVY5RGtYL2FhTlg1MFdMUFkKLS0tIDNCSGx1TGdBZExxa2VQTEVRcnBU
            ek4rQ1E3RFJWTGwzbTMvc1poK21BcVkKzrGHtJuVJvRCwXlqn8SrIkSG5CuyGRen
            Q/B8anIe+mER7cDKjnpqBnD/61Cf4+3VXOr0vsFtpkpL44xNF+k0DQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q2w07qws7tw5fhcsnxr33z6588exfnu2dpnsqhhqlvyxc0jf750qgrwv5t
    lastmodified: "2026-05-07T15:15:26Z"
    mac: ENC[AES256_GCM,data:6r89rR+1WDPEIISWSUZuCNZzuYDEbKksQwDTZoHBBjiCe9fKQCIHRa7TP74/POtFZl3ayRAItBSJq3HnmnCpgkwVSxS3H0fxF92gWWDE95gyU4LOiNgfszIivSMIN6vAYGHye1UexacagBFinPoNyhtd6KxFAYDJMtqW+S46uNI=,iv:T65glM9sNjkf/QdlARVPHC3XMVYppQDYJVRjqOHK6es=,tag:Zu7cD3lshIzwK568Nf+xnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
