strongswan_management_ip: ENC[AES256_GCM,data:RZIntJYNX60SqA==,iv:HFxJYpiWYz9oqNxEkNykm3VZx3eEb4BxG6chrLB7FIs=,tag:GEqBFVcKBU5lPFWwTIbxuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cnovY2E1WCtoT2IrbEsx
            OXd4Szg1bUR0WjFselN0MlJybmFYY3M1L0Q0CkdFalh0VlVCc0JydVhhWEZJVVgw
            VXV3K2VtYUJwWGdKeUxDMlVkdkEwTncKLS0tIFd2OHNHK0VyZ01naUFTYldvQlAx
            d0NkSkJMdjZtdjhXcGU3MnVqWXRaQ28KBJjtPEI5h4uXn4LAJUtmLfbkb7UjcJun
            bLAqqb9ArV8ou+ldNu8xoF74R3P8RpJiDurHlpNVQH6ZCL58brnE9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9qyhryg9zmwywfy92468knc2n5zr2j66e73kw5mzc28fs6m5u4qpazpma
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgQzd5N0pRIEJQL25sZ1JI
            MitwQnFuNSt2R05xb1NHWkdKSW5hZm1sVE82ejdqcHpaYjRINEl3TjJPSkdBTFVm
            Zzl5dE9TOHd3SXJqR1cyR2lHbFFobkdHdnBNRHRncwo2V1pQNFBMTVNRTHhCNktl
            TkdJL1lQL2ZRK0lmK1ZLTkIrcDZzVjZEb0RvCi0tLSAvTEtEbCtTMDV3d1R2SlIy
            RmZKRkV1TEFjbXptbTU2TnA4MFdiNVFZZHJJCgQRYgjyvxVIMvqVfY+fyDIPhCFm
            R3kqJDmuBxSpMdoxTFsNQuE3Sl6SzsY6ZhVIginWR7t8mO07IsZaseIDsew=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1q22yv67hk89v390rseukrx3mu5gzw9lpnngla4shn3efhzg2czn7cvdt8y3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYzZOcFNLNVFiUEhHMWhw
            d1NjZmR1V0ZxbkJqSE1VaUp6Q2xiZWZhcG1NCmFsZ1dLTy9QNlRuTWlqWEo0Snc3
            R0dKcHYvNkdiZFRVTmZNb1VrSUM0MVEKLS0tIDlyV2UwOUJTblpQcUVpTTF2dzM0
            cWFVeE43T3BjaERSK2k3R05uRjlBLzgKJQ+Pz03uGxI8PvLyYQTdh1cHI8APFhWE
            WdzXZ6mW0vkRB04by4lCaWQYsGYh9hXT+DfiZOszqmSci3YRjElGcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q2w07qws7tw5fhcsnxr33z6588exfnu2dpnsqhhqlvyxc0jf750qgrwv5t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgLzdQa2JRIEJIck1zcCt6
            Z0hwRVJmaDNadXNETmNUeGJnSG5UZ0NFeUs4ZXpNMTVwK0czbUJLUHpFS1JqTjRD
            TEUxcVNDVTk0cGczVGRpMlkzeFVhUmFRQVVHaXdYQQplQW94RDRKQllGSDF5d09h
            eGhUcXJWUFpTRERVUktTY2k3Mi9pMW1JMk93Ci0tLSBrWWNUYllNZm9HcVZzazJF
            RDZhejgySnRJOVREaGUwS2w1ZGtzbHZjaHlzCuxdpsJwR8tkNnjmoplVT+mpxnIu
            CJor7zhBRKjRGwLKX4IQtYxdwt5UdwdvMX6Q/AgmS0hyLt0tjfbUlzBgsDU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tpm1qdeuratg9kfm728u6kd278g7alwz3n6esmf4szyjcuwgrhqmlt0qg9u33se
    lastmodified: "2026-05-07T16:51:32Z"
    mac: ENC[AES256_GCM,data:0c7VomoCBmtNpTL/M6FXO76EB+N93EUM9HzlTK9B8ldqhFhnHp1ozXMPxrq7a1TxHN2HpxCRDuZAZ166svb/GYEabjKbD7UmYZlOmPQqXRlGlZITf1xEIaL0wK04FX7eds8Hdzc9UFaLKFR6Bvs5SmSRWFroW5c8TVe1W9Ae9lU=,iv:MNen9ote80AujXV66SYJiG4sYXeKdPnxw1Xvl3x/50U=,tag:+/WY2RuU8vdwB1vbfk5a+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
