strongswan_management_ip: ENC[AES256_GCM,data:RZIntJYNX60SqA==,iv:HFxJYpiWYz9oqNxEkNykm3VZx3eEb4BxG6chrLB7FIs=,tag:GEqBFVcKBU5lPFWwTIbxuw==,type:str]
sops:
    age:
        - recipient: age1q9qyhryg9zmwywfy92468knc2n5zr2j66e73kw5mzc28fs6m5u4qpazpma
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZisxUkVaVzVPZUEzK3Zt
            YzRpTXpaWEtrenkzTG1hcnl6bW02bWZMWUFrCkVMVklWeXNiTTZZekFhWXZWMDBS
            b0R6SE1leXR1U1JMcmVVSW5GSStTR00KLS0tIGxDQjNVcGtCWXdsa2FHNEE2STlJ
            djVLNk1YWGFoTWhzVTJZK3VxWHpENGsKmZWSeV6h0TWYMqXG8mpZx6411bGo9fSw
            sYVttuiY9qC4ky0yG0TKu7JxcteGWYNBiYPVa4xKXLB2fuDz8u+f2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q2w07qws7tw5fhcsnxr33z6588exfnu2dpnsqhhqlvyxc0jf750qgrwv5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Um9vWHU1Sm4yM004ZTdK
            R0Q2aXBXZWg4RjZoaUpnZkRFUlpsN1FnQlZRClZua2QxZStuWEV2NWF0eHB3T0NR
            aFI1Uk14YnRyNzlNbVVuR2RLQVVUNkEKLS0tIEFyK3hxN1FoeC92NWJvcFNadk1E
            cWI3elkySGRzTmRheXUvd1JVYTRwMlkK/aDC/j5BcTy2E7Oo0Ma4TFdc6RfcKQc8
            YpxOAvng1ojiPwWWpZWU4W4VWK2zeKfbIqRZPdWsvRKRcIPK7kMPvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T16:51:32Z"
    mac: ENC[AES256_GCM,data:0c7VomoCBmtNpTL/M6FXO76EB+N93EUM9HzlTK9B8ldqhFhnHp1ozXMPxrq7a1TxHN2HpxCRDuZAZ166svb/GYEabjKbD7UmYZlOmPQqXRlGlZITf1xEIaL0wK04FX7eds8Hdzc9UFaLKFR6Bvs5SmSRWFroW5c8TVe1W9Ae9lU=,iv:MNen9ote80AujXV66SYJiG4sYXeKdPnxw1Xvl3x/50U=,tag:+/WY2RuU8vdwB1vbfk5a+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
