strongswan_management_ip: ENC[AES256_GCM,data:RZIntJYNX60SqA==,iv:HFxJYpiWYz9oqNxEkNykm3VZx3eEb4BxG6chrLB7FIs=,tag:GEqBFVcKBU5lPFWwTIbxuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZjAyeWZacWVKNlFZeFpL
            MytFMGlCL3BQMFRvY0QxZ2k5TmswdExyZXdVCngybFZkampUSEdqT0pneldETkla
            ZldDREtTNHdZdEJXbWJvNmtRTHNYR3cKLS0tIHhhSXVDaTdUb3JsL0xHS3pscURN
            bTV3QjBmSy9LY0ZVNlYxeVlZYzZrQlkKgvtlMp11H+P2kgCT96H3BZfFyQ2wzdwy
            PePK5C3UWeXVHuL6LbxbwCSxYQCQzcieh1nQVHOD+gaSCGSWVycnzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9qyhryg9zmwywfy92468knc2n5zr2j66e73kw5mzc28fs6m5u4qpazpma
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgK1dBbzlBIEJFWVNmMU8y
            VG51ekFwdzVLWHByVmpNTVgzR2pXUEJad1BiYnN2N05jaXR5bUZ4alRwMGFER0FM
            d00xNEVIdHJlTDExbk10cU91Y2ExRDE1WGNGN3pKawpIQTZOOXQrT0V4Z3NaT0l1
            UDR2bmh4Z3Y0UVlSb2hnZ21NVjdXTUI1aG9BCi0tLSBRMHVkNkpJV1NxMXNXd1dw
            WU5iSU9HVTJQWmpaanE2NzN2WGVjSDVtYm93CsPoQixEL8O2kSGc7Okg0yEQaYg9
            PJGyiwkDR/jHcUeMk6jJsaj2XhTif9Tp6SmCSFQlQDYKpQY1rZApAQ6aYPA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1q22yv67hk89v390rseukrx3mu5gzw9lpnngla4shn3efhzg2czn7cvdt8y3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcHRPbXB2VHlOZlZsbVNm
            aUZUazJuTlVJQ05YdG1FMmR6YkRVVW5UMFRFCmZZVFlCei9kdXh3ZDRkTWlhWlVs
            enNEa3RpRGhoZTR4RTZmNEJlNlE4Z28KLS0tIGFwOUNqeEMvcWRZa1ZUNkcwdHA4
            TDdVZ1k1bHlLZitrSUJIYmtvY2FkTkkKCXQ/I4Tohy0VeH8aybhRpv0yI+s3sfQe
            s1dzlPrepjS1gWEpadcMPrO7Vh6OabMIE9En/hrCVcv16/GF4uiH0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q2w07qws7tw5fhcsnxr33z6588exfnu2dpnsqhhqlvyxc0jf750qgrwv5t
    lastmodified: "2026-05-07T16:51:32Z"
    mac: ENC[AES256_GCM,data:0c7VomoCBmtNpTL/M6FXO76EB+N93EUM9HzlTK9B8ldqhFhnHp1ozXMPxrq7a1TxHN2HpxCRDuZAZ166svb/GYEabjKbD7UmYZlOmPQqXRlGlZITf1xEIaL0wK04FX7eds8Hdzc9UFaLKFR6Bvs5SmSRWFroW5c8TVe1W9Ae9lU=,iv:MNen9ote80AujXV66SYJiG4sYXeKdPnxw1Xvl3x/50U=,tag:+/WY2RuU8vdwB1vbfk5a+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
