cluster_allowed_ips:
    leo-naeka-home:
        ip: ENC[AES256_GCM,data:6MHDVL+aaRVPOrp2vg==,iv:yFyWMDdA1NI5KbWQwTtr769X/V7ZP4kbhEpNO+nL6Hk=,tag:m0ufYxhoSuG+tZ/jo7fwwQ==,type:str]
    leo-naeka-office:
        ip: ENC[AES256_GCM,data:ydvBIP75qKdFNEaVE1U=,iv:5yXkd6FOBZY0nvqZyG1HoMpDcmbEjVILBez9yc3vj1M=,tag:6z7osvSkd/mXw47iJidtSA==,type:str]
    xavfernandez-home:
        ip: ENC[AES256_GCM,data:1ESaS2o7UDwTP4ut64Ad,iv:/IOWh0Cbf49b1DaVDBIEcXApIlL3MZvAR200IwQll9I=,tag:BEyVqf0jXRQorlvfhLf+HA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QzJzNk9FeElqMFV6OHR2
            YzNqc3RlaUpmd2JYYVN1RFBKZWRTUWJieVNNCko0b25FSXh4bXAyWTYvRHdxbFFZ
            WW4yRG16TTFDazlxeG9Kc2VDRklVZFEKLS0tIDFOZC8zZ2tZTG9XakliU1JiakIy
            Ti9XYlhFSmo1RGVIUmJ3My9LV1dvU3MKpvl/bNI8h42Cb8/lQYWFybmSXkpw03D/
            TMSBgzA+wlEmRz6ou/appLTPruBPkN/zo9DnuS6Zxcx6INNy2dsOcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9qyhryg9zmwywfy92468knc2n5zr2j66e73kw5mzc28fs6m5u4qpazpma
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgYkRodG9BIEJHUzVjWXh2
            Nk9oNGVHOVRqdHRRMlh6QVIzd1JTNkpxUWZFV1doWVFlZ0pxcmJQL3pOS1VaR1RX
            ek9CTmh0S013aXhxcG1sd3JWYklXWkFsNlR4dFNOcwpMVGRlOWVVVHZBa1pXalZ4
            QUY2K3EyeEZoQXRGZzRpc1RGLzdUUVZMS1dzCi0tLSBUb3FybEVYRXMzZkhFOEs4
            RS9vaDJkSHF6ZWIrRzNkUURYc2t0cFFDSHBjCsSYkOa1maO8Bxm401j/zw27H4hw
            OgtInZclHh0wPy+7n9z4SSlxuoepsSJmkqfrVFNq7chLcSTKnD4JxzUabMY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1q22yv67hk89v390rseukrx3mu5gzw9lpnngla4shn3efhzg2czn7cvdt8y3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRm12RGIxRkJsa2VEQTAv
            ek9RbHBPdGVVUGN1V3dacFZFczB3QXpjb1c0CmhWbHpOUDhmRXkxaFM5S1RkVkNI
            VXh4Zlo3eG82dlc2a2tFdUZpNXJ3OVkKLS0tIHBZdjZOazFWck9mWFQyYnJUa1V1
            eVVtWk5JbEVFWGpKU3czcUhMQjd3ZVkKCvJ4Bl0qjb1iNehG6+1quXFtye8CG+3g
            /XxkyDbJw1G7mjLQcbt7H5w4I0ttlTQrRfVzS/+DwL5yTUJy8kjaGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q2w07qws7tw5fhcsnxr33z6588exfnu2dpnsqhhqlvyxc0jf750qgrwv5t
    lastmodified: "2026-06-12T20:39:07Z"
    mac: ENC[AES256_GCM,data:q6nOlQB1F1lk1S7abCQm0zO8iTNcMDYKCBxfz6S9DaicvCH9oDGvQG6bXz/jL9PIPQMLY9iy/SrGPYZg0OFw2M1jrFqiznFQ10Muy+aS25+h/dhKmMtEz0XDdtdjOUUgvewUcoJ3MSPxMLeeWCuKEn6dmsJaacOpcKDfaMbRi3M=,iv:in0ZvRq+wo+3cnlXw9CCnzwEufYwFi0VZ3CMp06iD+o=,tag:0SZc/VguISg+JOxLEajiBw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
