cluster_allowed_ips:
    leo-naeka-home:
        ip: ENC[AES256_GCM,data:6MHDVL+aaRVPOrp2vg==,iv:yFyWMDdA1NI5KbWQwTtr769X/V7ZP4kbhEpNO+nL6Hk=,tag:m0ufYxhoSuG+tZ/jo7fwwQ==,type:str]
    leo-naeka-office:
        ip: ENC[AES256_GCM,data:ydvBIP75qKdFNEaVE1U=,iv:5yXkd6FOBZY0nvqZyG1HoMpDcmbEjVILBez9yc3vj1M=,tag:6z7osvSkd/mXw47iJidtSA==,type:str]
    xavfernandez-home:
        ip: ENC[AES256_GCM,data:1ESaS2o7UDwTP4ut64Ad,iv:/IOWh0Cbf49b1DaVDBIEcXApIlL3MZvAR200IwQll9I=,tag:BEyVqf0jXRQorlvfhLf+HA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobUMxTUp1aWNxcFIybVZp
            QmhpRkpJOG5nV25Qak1qWFYxcnZlNzZ4SmkwClB1NXY1TkNnSllOZkJTdk1OK3Ex
            U29hNjFUZ1QxUzlNNEhycUZkcmhBVDgKLS0tIFZxV1ZQZGhUbWtGSkQ3Ynk2djBG
            NEo4alp6NDFPZlI2RE53WGxOcGxYQXcKjoMwPA/oIbtdMQSOrOqtF9bqbgiG0FW9
            3ShkTso9+oY9vJ5Cgg5vmVFPrwt4y9N5soKDPMgYptKobbQ6Dwn1xA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q9qyhryg9zmwywfy92468knc2n5zr2j66e73kw5mzc28fs6m5u4qpazpma
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK2l4TzhWZ3RrWHpaWTVn
            aWZLNm9laGxIY1B4UWZwTjBqUDBtKzJLQ2xFCjQ2Yi9RZDJ2cURDekJrbzhSalRO
            ek1KR2dPNkxhRlhDQXlteXh5UFdodGMKLS0tIGlHdTVQUTRLZHp6Rk1ST3hDZ1ZG
            Z3djMWhNUEZuL1VvRkY2ZW55bk1ZMk0K32Lc/zBHTvzJgoEzbgMicaT6eequ8pGd
            uGwVNB/oh0OtKu8RBP3/uvBKYTYpyTTtsMI7oTp/67qTOcXLTjz2gQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q2w07qws7tw5fhcsnxr33z6588exfnu2dpnsqhhqlvyxc0jf750qgrwv5t
    lastmodified: "2026-06-12T20:39:07Z"
    mac: ENC[AES256_GCM,data:q6nOlQB1F1lk1S7abCQm0zO8iTNcMDYKCBxfz6S9DaicvCH9oDGvQG6bXz/jL9PIPQMLY9iy/SrGPYZg0OFw2M1jrFqiznFQ10Muy+aS25+h/dhKmMtEz0XDdtdjOUUgvewUcoJ3MSPxMLeeWCuKEn6dmsJaacOpcKDfaMbRi3M=,iv:in0ZvRq+wo+3cnlXw9CCnzwEufYwFi0VZ3CMp06iD+o=,tag:0SZc/VguISg+JOxLEajiBw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
