cluster_allowed_ips:
    leo-home:
        ip: ENC[AES256_GCM,data:S7ezPMcBNAZ9BP3r6w==,iv:JOYJ2vlISQLdkbvRqLDjC6g5Vr3BKdh+nLTUN9olZEI=,tag:cCQhRP9ltdvhpb+uQx7SpQ==,type:str]
    leo-office:
        ip: ENC[AES256_GCM,data:JN95t8532nREmTPBCmY=,iv:yCNQ/EfZlCAS1DYCepVIWYRlLWZgl7Yatp10qIWEMis=,tag:9feN8qAkbrZZ+g3J6VlWhA==,type:str]
sops:
    age:
        - recipient: age1q9qyhryg9zmwywfy92468knc2n5zr2j66e73kw5mzc28fs6m5u4qpazpma
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobUMxTUp1aWNxcFIybVZp
            QmhpRkpJOG5nV25Qak1qWFYxcnZlNzZ4SmkwClB1NXY1TkNnSllOZkJTdk1OK3Ex
            U29hNjFUZ1QxUzlNNEhycUZkcmhBVDgKLS0tIFZxV1ZQZGhUbWtGSkQ3Ynk2djBG
            NEo4alp6NDFPZlI2RE53WGxOcGxYQXcKjoMwPA/oIbtdMQSOrOqtF9bqbgiG0FW9
            3ShkTso9+oY9vJ5Cgg5vmVFPrwt4y9N5soKDPMgYptKobbQ6Dwn1xA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q2w07qws7tw5fhcsnxr33z6588exfnu2dpnsqhhqlvyxc0jf750qgrwv5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK2l4TzhWZ3RrWHpaWTVn
            aWZLNm9laGxIY1B4UWZwTjBqUDBtKzJLQ2xFCjQ2Yi9RZDJ2cURDekJrbzhSalRO
            ek1KR2dPNkxhRlhDQXlteXh5UFdodGMKLS0tIGlHdTVQUTRLZHp6Rk1ST3hDZ1ZG
            Z3djMWhNUEZuL1VvRkY2ZW55bk1ZMk0K32Lc/zBHTvzJgoEzbgMicaT6eequ8pGd
            uGwVNB/oh0OtKu8RBP3/uvBKYTYpyTTtsMI7oTp/67qTOcXLTjz2gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T15:26:45Z"
    mac: ENC[AES256_GCM,data:BydO7/EzV5yhIlDwMb6XlzZe6/obtXWMcoKJAHaTDOUmKfbDs6RuukpT9U29FBADPHAM8J8n6Oi+R9Pf4xb22ZNtgkaJtMqsuFUtGZQN6t6CkeEzdgb/dMqY3qAKkQ43OpNPVGFBjp7ZsVuhtINIY/XyfrnNkZC4HB/Xt3l9qE0=,iv:JQFQMajECYDoeV72umIdz/FTeeCOvF6URljIYfN4YZE=,tag:nqS/pdJ4yeFuzFa+0jiSmA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
