name: Terraform apply
on:
  push:
    branches:
      - main

permissions: {}

env:
  SCW_ACCESS_KEY: ${{ secrets.SCW_TF_CI_ACCESS_KEY }}
  SCW_SECRET_KEY: ${{ secrets.SCW_TF_CI_SECRET_KEY }}
  SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
  SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
  # ⬇ This one (legacy) seems still required by iam...
  SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.SCW_TF_CI_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_TF_CI_SECRET_KEY }}

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
      - name: Terraform apply
        run: make terraform-apply-all
