name: Terraform apply
on:
  push:
    branches:
      - 'main'

env:
  TF_VAR_scw_organization_id: ${{ secrets.SCW_ORGANIZATION_ID }}
  TF_VAR_scw_access_key: ${{ secrets.SCW_TF_CI_ACCESS_KEY }}
  TF_VAR_scw_secret_key: ${{ secrets.SCW_TF_CI_SECRET_KEY }}

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
      - name: Terraform init
        run: >
          terraform init -input=false
            -backend-config "access_key=$TF_VAR_scw_access_key"
            -backend-config "secret_key=$TF_VAR_scw_secret_key"
            -no-color
      - name: Terraform apply
        run: terraform apply -input=false -no-color
