name: Terraform plan
on:
  pull_request:
  merge_group:

permissions:
  contents: read

env:
  TF_VAR_scw_organization_id: ${{ secrets.SCW_ORGANIZATION_ID }}
  TF_VAR_scw_access_key: ${{ secrets.SCW_TF_CI_ACCESS_KEY }}
  TF_VAR_scw_secret_key: ${{ secrets.SCW_TF_CI_SECRET_KEY }}

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
      - name: Terraform fmt
        run: terraform fmt -check
      - name: Terraform init
        run: >
          terraform init
          -input=false
          -backend-config "access_key=$TF_VAR_scw_access_key"
          -backend-config "secret_key=$TF_VAR_scw_secret_key"
          -no-color
      - name: Terraform validate
        run: terraform validate -no-color
      - name: Terraform plan
        run: terraform plan -input=false -no-color
